### ISSUE TITLE
Triggering read the docs

### ISSUE THREAD

**Issue by bmorris3** [alphapsa/PIPE#4]
To get RTD running, could you please [follow these instructions](https://docs.readthedocs.io/en/stable/webhooks.html) and add a webhook with this URL (https://readthedocs.org/api/v2/webhook/pipe-cheops/148964/) to the PIPE repo?

**Comment by alphapsa** [comment]
You seem to be on top of things, so I made it public.

**Comment by bmorris3** [comment]
Fantastic! Docs are building [here](https://pipe-cheops.readthedocs.io/en/latest/), I'll do some heavy construction on these webpages/source code over the next week or two.

**Comment by bmorris3** [comment]
Also – you may want to put the link to the docs (https://pipe-cheops.readthedocs.io/en/latest/) in the "About" textbox located here in the github repo:

![image](https://user-images.githubusercontent.com/3497584/110593763-46484000-817c-11eb-8761-96987c69a0d3.png)
